name: Benchmarks

on:
  push:
    branches:
      - master

jobs:
  performance:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        compiler: [gcc-11, gcc-12, gcc-13, clang-16, clang-17]

    steps:
      - uses: actions/checkout@v3

      - name: Make install script executable
        run: chmod +x scripts/install_compiler.sh

      - name: Install compiler
        run: bash scripts/install_compiler.sh ${{ matrix.compiler }}
        env:
          compiler: ${{ matrix.compiler }}

      - uses: actions/setup-python@v4
        with: { python-version: "3.8" }

      - name: Build and Configure
        run: bash scripts/build-clean.sh performance-ubuntu

      - name: Test
        working-directory: build
        run: ctest --output-on-failure --no-tests=error

      - name: Performance
        run: |
          ./build/benchmark/expected64_benchmark > out.txt
          python3 scripts/parse_catch2_benchmarks.py out.txt > benchmark_results_${{ matrix.compiler }}.html

      - name: Save Benchmark Results as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: benchmark-results-${{ matrix.compiler }}
          path: benchmark_results_${{ matrix.compiler }}.html
  deploy:
    needs: performance
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Download all Artifacts
        uses: actions/download-artifact@v2

      - name: Deploy to GitHub Pages
        run: |
          # Setup Git
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          # Clone a fresh copy of the repo in a separate directory
          git clone https://github.com/${{ github.repository }}.git repo-copy
          cd repo-copy

          # Checkout gh-pages branch
          git checkout gh-pages

          # Copy the benchmark results from the previous step
          cp ../benchmark-results-*/*.html .

          # Add all changes to staging
          git add -A

          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update Benchmark Results"
            git push origin gh-pages
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
